name: First Workflow
on: 
  workflow_dispatch:
  pull_request:
    types:
      - open
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: step1
          run: echo "Hi step1"
        - name: step2
          run: echo "Hi step2"
  two-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: 2_step1
        run: |
          echo "fist line"
          echo "second line"
