name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
        - name: step1
          run: echo "Hi step1"
        - name: step2
          run: echo "Hi step2"
