name: Install Python Lib
on: workflow_dispatch
env:
  VARIABLE_A: variable_value
  REPO_SECRET: ${{ secrets.REPO_SECRET }}
jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
      - name: install lib
        run: |
          sudo apt update
          sudo apt install python3
      - name: get python version
        run: |
          python3 --version
      - name: get code
        uses: actions/checkout@v3
      - name: get path
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          ls -l $GITHUB_WORKSPACE
      - name: run python script
        run: python3 $GITHUB_WORKSPACE/print.pyxe
      - name: test failure1
        if: failure()
        run: echo "Failure1"
      - name: test failure2
        run: echo "Failure2"
