name: par1
run-name: par1
on: 
  workflow_dispatch:
    inputs:
      TGT_ENV:
        description: "Environment"
        required: false
        default: "DEV"

concurrency:
  group: par1
  cancel-in-progress: false
jobs:
  job1:
    concurrency:
      group: ${{ inputs.TGT_ENV }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:  
      - name: step1
        run: |
          echo step1 start "$(date)"
          sleep 50
          echo step1 end "$(date)"
  job2:
    concurrency:
      group: ${{ inputs.TGT_ENV }}
      cancel-in-progress: false
    needs: [job1]
    runs-on: ubuntu-latest
    steps:  
      - name: step2
        run: |
          echo step2 start "$(date)"
          sleep 50
          echo step2 start "$(date)"
  job3:
    concurrency:
      group: ${{ inputs.TGT_ENV }}
      cancel-in-progress: false
    needs: [job1,job2]
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: |
          echo step3 start "$(date)"
          sleep 100
          echo step3 end "$(date)"
